### PR TITLE
Issue #21

### PR DESCRIPTION
**Pull request by geekskick**

### CODE REVIEW

**Comment by binkiklou** [comment]
Do you have any other pr to do, because I am making this private soon

**Comment by geekskick** [comment]
I have been working on adding some unit tests on a local branch however this isn't complete. Happy to go with what you want, if you're not interested I will sack it off, but its you want the progress I have made I can share it with you. Just let me know :-)

**Comment by binkiklou** [comment]
Do you have a discord account ?

**Comment by geekskick** [comment]
For sure, I'll join the project discord

**Pull request merged**
